/* Only deliberately published invitation fields are rendered here. */
const VYBE_INVITE_TOKEN=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function vybeLaunchInvitation(){const params=new URLSearchParams(location.search),start=new URLSearchParams(window.Telegram?.WebApp?.initData||'').get('start_param')||params.get('tgWebAppStartParam')||'';const token=params.get('invite')||(/^plan_/.test(start)?start.slice(5):'');return VYBE_INVITE_TOKEN.test(token)?token.toLowerCase():null;}
function createVybePlanExtras({api,publicApi,getLang,telegram,onPlan,onJoin,onExit,analytics=()=>{}}){
  let root=null,epoch=0,closed=true,back=null;
  const tr=(uk,en)=>getLang()==='en'?en:uk,esc=v=>escapeHtml(String(v??'')),find=id=>root?.querySelector('#'+id),alive=e=>!closed&&root?.isConnected&&epoch===e;
  const error=code=>code==='PLAN_INVITE_UNAVAILABLE'?tr('Запрошення вимкнено, зустріч уже почалася або план недоступний.','The invitation is disabled, the meetup has started, or the plan is unavailable.'):tr('Не вдалося завантажити. Спробуй ще раз.','Could not load. Please try again.');
  function dispose(){epoch++;closed=true;root=null;back=null;}
  function mount(target,onBack){dispose();closed=false;root=target;back=onBack;return epoch;}
  function header(title){return '<header class="planHead"><button id="extrasBack" class="planBack" type="button" aria-label="'+tr('Назад','Back')+'">‹</button><h2>'+esc(title)+'</h2><button id="extrasExit" class="planExit" type="button" aria-label="'+tr('Закрити','Close')+'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button></header>';}
  function bindHeader(){find('extrasBack').onclick=()=>back?.();find('extrasExit').onclick=onExit;}
  function card(p){const c=VYBE_PLAN_CATEGORIES.find(x=>x[0]===p.category)||VYBE_PLAN_CATEGORIES[6],when=new Date(p.starts_at).toLocaleString(getLang()==='en'?'en-GB':'uk-UA',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});return '<article class="inviteCard"><span class="inviteEyebrow">VYBE · '+esc(c[getLang()==='en'?3:2])+'</span><div class="inviteIcon" aria-hidden="true">'+c[1]+'</div><h3>'+esc(p.title)+'</h3><p class="planWhen">'+esc(when)+'</p><p>📍 '+esc(p.city)+(p.visibility==='public'?' · '+esc(p.venue_label):' · '+tr('Приватна локація','Private venue'))+'</p><div class="planBadges"><em>'+esc(tr('Ще '+Math.max(0,p.capacity-p.approved_count)+' місць',Math.max(0,p.capacity-p.approved_count)+' seats left'))+'</em><em>'+tr('Участь після схвалення','Host approval required')+'</em></div></article>';}
  async function preview(target,token,authenticated){const e=mount(target,onExit);root.innerHTML=header(tr('Тебе запросили','You are invited'))+'<div class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div>';bindHeader();let r;try{r=authenticated?await api('plans_invite_preview',{token}):await publicApi(token);}catch{r={ok:false};}if(!alive(e))return;
    if(!r.ok){root.innerHTML=header(tr('Запрошення недоступне','Invitation unavailable'))+'<div class="planScroll"><p class="planEmpty">'+esc(error(r.error))+'</p><button id="inviteRetry" class="choice" type="button">'+tr('Спробувати ще раз','Try again')+'</button></div>';bindHeader();find('inviteRetry').onclick=()=>preview(root,token,authenticated);return;}
    root.innerHTML=header(tr('Тебе запросили','You are invited'))+'<div class="planScroll">'+card(r.plan)+'<p class="planHint">'+tr('Точне місце та учасники відкриються після схвалення. Для заявки потрібна анкета 18+ з фото.','Meeting details and members unlock after approval. An 18+ profile with a photo is required to apply.')+'</p><button id="inviteJoin" class="primary" type="button">'+tr('Хочу приєднатися','I want to join')+'</button></div>';bindHeader();find('inviteJoin').onclick=()=>onJoin(token);analytics('plan_invitation_viewed',{category:r.plan.category});
  }
  async function invitation(target,id,host){const e=mount(target,()=>onPlan(id));root.innerHTML=header(tr('Запрошення на план','Plan invitation'))+'<div class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div>';bindHeader();
    const r=await api(host?'plans_invite_get':'plans_share',{plan_id:id});if(!alive(e))return;
    if(!r.ok){root.querySelector('.planScroll').innerHTML='<p class="planEmpty">'+esc(error(r.error))+'</p>';return;}
    const enabled=host?r.enabled:true;
    root.innerHTML=header(tr('Запрошення на план','Plan invitation'))+'<div class="planScroll">'+(host?card(r.plan):'')+(host?'<p class="planHint">'+tr('Увімкнувши посилання, ти дозволяєш будь-кому переглядати назву, час, формат, місто, кількість місць і назву публічного закладу. Перевір, що ці поля не містять домашньої адреси чи контактів.','Enabling this link lets anyone view the title, time, category, city, seat count and public venue name. Check these fields contain no home address or contact details.')+'</p><button id="inviteToggle" class="choice" type="button">'+(enabled?tr('Вимкнути запрошення','Disable invitation'):tr('Увімкнути запрошення','Enable invitation'))+'</button>':'')+(enabled?'<button id="inviteShare" class="primary" type="button">'+tr('Поділитися у Telegram','Share in Telegram')+'</button><button id="inviteCopy" class="choice" type="button">'+tr('Скопіювати посилання','Copy link')+'</button><p id="inviteLink" class="planHint"></p>':'')+'<p id="extrasError" class="planError" role="status"></p></div>';bindHeader();
    find('inviteToggle')?.addEventListener('click',async()=>{find('inviteToggle').disabled=true;const result=await api('plans_invite_update',{plan_id:id,enabled:!enabled});if(!alive(e))return;if(!result.ok){find('inviteToggle').disabled=false;find('extrasError').textContent=error(result.error);return;}await invitation(root,id,host);});
    let shared=host?null:r,loading=null;
    const getShare=async native=>{if(shared&&!native)return shared;if(loading)return loading;loading=api('plans_share',{plan_id:id,native}).then(data=>{if(data.ok)shared=data;return data;}).finally(()=>{loading=null;});return loading;};
    find('inviteShare')?.addEventListener('click',async()=>{const button=find('inviteShare');if(button.disabled)return;button.disabled=true;const native=typeof telegram?.shareMessage==='function'&&telegram.isVersionAtLeast?.('8.0')!==false,r=await getShare(native);if(!alive(e))return;button.disabled=false;if(!r.ok){find('extrasError').textContent=error(r.error);return;}try{if(native&&r.prepared_id){telegram.shareMessage(r.prepared_id,sent=>{if(sent&&alive(e))analytics('plan_invitation_shared',{method:'telegram'});});}else{telegram?.openTelegramLink?.('https://t.me/share/url?url='+encodeURIComponent(r.url)+'&text='+encodeURIComponent(r.text));analytics('plan_invitation_share_opened',{method:'link'});}}catch{find('inviteLink').textContent=r.url;find('extrasError').textContent=tr('Скопіюй посилання кнопкою нижче.','Copy the link using the button below.');}});
    find('inviteCopy')?.addEventListener('click',async()=>{const r=await getShare(false);if(!alive(e))return;if(!r.ok){find('extrasError').textContent=error(r.error);return;}find('inviteLink').textContent=r.url;try{await navigator.clipboard.writeText(r.url);if(alive(e))find('extrasError').textContent=tr('Посилання скопійовано.','Link copied.');}catch{if(alive(e))find('extrasError').textContent=tr('Натисни й утримуй посилання, щоб скопіювати.','Press and hold the link to copy it.');}});
  }
  async function planning(target,id){const e=mount(target,()=>onPlan(id));root.innerHTML=header(tr('Не пропустити зустріч','Remember the meetup'))+'<div class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div>';bindHeader();const r=await api('plans_reminder_get',{plan_id:id});if(!alive(e))return;
    if(!r.ok){root.querySelector('.planScroll').innerHTML='<p class="planEmpty">'+esc(error(r.error))+'</p>';return;}
    root.innerHTML=header(tr('Не пропустити зустріч','Remember the meetup'))+'<div class="planScroll"><section class="inviteCard"><h3>'+tr('План у твоєму календарі','Add it to your calendar')+'</h3><p class="planHint">'+tr('Завантаж файл зустрічі й відкрий його у календарі. Домашня адреса та список учасників у файл не потрапляють.','Download the event file and open it in your calendar. Home addresses and member lists are omitted.')+'</p><button id="planCalendar" class="primary" type="button">'+tr('Завантажити для календаря','Download calendar event')+'</button></section><section class="inviteCard"><h3>'+tr('Нагадування','Reminder')+'</h3><p class="planHint">'+tr('Приблизно за годину до початку. Якщо лишилося менше години — найближчими хвилинами. У Telegram — якщо дозволено сповіщення про повідомлення.','About an hour before the meetup, or within the next few minutes if it starts sooner. Telegram delivery follows your message notification setting.')+'</p><button id="planReminder" class="choice" type="button" aria-pressed="'+String(r.enabled)+'">'+(r.enabled?tr('Вимкнути нагадування','Disable reminder'):tr('Нагадати перед зустріччю','Remind me before the meetup'))+'</button>'+(r.delivered?'<p class="planHint">'+tr('Нагадування вже є у сповіщеннях VYBE.','The reminder is already in VYBE notifications.')+'</p>':'')+'</section><p id="extrasError" class="planError" role="status"></p></div>';bindHeader();
    find('planReminder').onclick=async()=>{find('planReminder').disabled=true;const result=await api('plans_reminder_set',{plan_id:id,enabled:!r.enabled});if(!alive(e))return;if(!result.ok){find('planReminder').disabled=false;find('extrasError').textContent=error(result.error);return;}await planning(root,id);};
    find('planCalendar').onclick=async()=>{const button=find('planCalendar');if(button.disabled)return;button.disabled=true;const result=await api('plans_calendar',{plan_id:id});if(!alive(e))return;button.disabled=false;if(!result.ok){find('extrasError').textContent=error(result.error);return;}try{if(typeof telegram?.downloadFile==='function'&&telegram.isVersionAtLeast?.('8.0')!==false)telegram.downloadFile({url:result.url,file_name:result.filename});else{const a=document.createElement('a');a.href=result.url;a.download=result.filename;a.target='_blank';a.rel='noopener noreferrer';a.click();}}catch{find('extrasError').textContent=tr('Не вдалося відкрити завантаження. Спробуй ще раз.','Could not open the download. Please try again.');}};
  }
  return {preview,invitation,planning,dispose,back(){if(!closed&&root?.isConnected){back?.();return true;}return false;},isMounted:()=>!closed&&!!root?.isConnected};
}
