/* Meetups are separate from romantic matches. Private addresses stay in memory. */
const VYBE_PLAN_CATEGORIES=Object.freeze([
  ['pizza','🍕','Піца','Pizza'],['pub','🍻','Паб','Pub'],['walk','🌳','Прогулянка','Walk'],
  ['celebration','🎂','Святкування','Celebration'],['party','🎉','Тусовка','Party'],
  ['outdoors','🏕️','На природі','Outdoors'],['other','✨','Інше','Other']
]);
function vybePlanLocalDate(date=new Date()){
  return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);
}
function vybePlanTimeRange({date,allDay=true,from='18:00',to='23:00'}){
  if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date))return null;
  const [year,month,day]=date.split('-').map(Number);
  const local=(clock)=>{
    if(typeof clock!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(clock))return null;
    const [hour,minute]=clock.split(':').map(Number),value=new Date(year,month-1,day,hour,minute);
    return value.getFullYear()===year&&value.getMonth()===month-1&&value.getDate()===day&&value.getHours()===hour&&value.getMinutes()===minute?value:null;
  };
  const start=local(allDay?'00:00':from),end=allDay?new Date(year,month-1,day+1):local(to);
  if(!start||!end||!Number.isFinite(end.getTime())||end<=start)return null;
  return {starts_from:start.toISOString(),starts_before:end.toISOString()};
}
function createVybePlans({api,getLang,getProfile,onPeople,onProfile,onSafety,onExtras=()=>{},onExit=()=>{},confirm,analytics=()=>{}}){
  const tr=(uk,en)=>getLang()==='en'?en:uk, esc=value=>escapeHtml(String(value??''));
  const cat=id=>VYBE_PLAN_CATEGORIES.find(x=>x[0]===id)||VYBE_PLAN_CATEGORIES[6];
  const catLabel=id=>{const c=cat(id);return c[1]+' '+c[getLang()==='en'?3:2]};
  const nonce=()=>crypto.randomUUID();
  let root=null,epoch=0,map=null,markers=null,timer=null,refreshTimer=null,busy=false,closed=true;
  let view='map',previous='map',center=null,zoom=12,category='',when=null,plans=[],draft=null,detail=null,messageRetry=null;
  const find=id=>root?.querySelector('#'+id),alive=token=>!closed&&root?.isConnected&&token===epoch;
  const errorText=code=>({PLAN_FULL:tr('Місця вже зайняті.','All seats are taken.'),PLAN_CLOSED:tr('План завершено або скасовано.','This plan has ended or was cancelled.'),PLAN_LIMIT:tr('Можна мати до 5 активних планів.','You can have up to 5 active plans.'),INVALID_PLAN_TIME:tr('Обери майбутній час у межах 90 днів.','Choose a future time within 90 days.'),PLAN_PROFILE_REQUIRED:tr('Спершу заповни анкету 18+ з фото.','Complete your 18+ profile with a photo first.'),PLAN_REQUEST_DECLINED:tr('Організатор відхилив заявку.','The host declined your request.'),PLAN_RETRY_CHANGED:tr('Попередній запит уже збережено. Онови план.','The previous request was saved. Refresh the plan.'),PLAN_UNAVAILABLE:tr('План недоступний.','This plan is unavailable.'),PLAN_JOIN_REQUIRED:tr('Чат доступний після схвалення заявки.','Chat is available once your request is approved.')})[code]||tr('Не вдалося завантажити. Спробуй ще раз.','Could not load. Please try again.');
  const status=id=>({host:tr('Ти організатор','You are the host'),pending:tr('Заявка на розгляді','Request pending'),approved:tr('Тебе схвалено','You are approved'),rejected:tr('Заявку відхилено','Request declined'),left:tr('Ти вийшов/-ла','You left')})[id]||'';
  const time=iso=>new Date(iso).toLocaleString(getLang()==='en'?'en-GB':'uk-UA',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
  function clearPage(){epoch++;busy=false;clearTimeout(timer);clearInterval(refreshTimer);timer=refreshTimer=null;if(map){center=[map.getCenter().lat,map.getCenter().lng];zoom=map.getZoom();map.remove();map=null;}markers=null;}
  function dispose(){clearPage();root?.removeEventListener('click',exit);root=null;closed=true;draft=null;detail=null;messageRetry=null;plans=[];}
  function top(title,subtitle='',back=true){return '<header class="planHead">'+(back?'<button id="planBack" type="button" class="planBack" aria-label="'+tr('Назад','Back')+'">‹</button>':'')+'<div><h2>'+esc(title)+'</h2>'+(subtitle?'<p>'+esc(subtitle)+'</p>':'')+'</div><button id="planExit" type="button" class="planExit" aria-label="'+tr('Закрити плани','Close plans')+'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button></header>';}
  function page(html,mode){clearPage();view=mode;root.innerHTML=html;find('planBack')?.addEventListener('click',back);return epoch;}
  function options(selected){return VYBE_PLAN_CATEGORIES.map(c=>'<option value="'+c[0]+'" '+(selected===c[0]?'selected':'')+'>'+esc(catLabel(c[0]))+'</option>').join('');}
  function card(p){const free=Math.max(0,Number(p.capacity)-Number(p.approved_count));return '<button type="button" class="planCard" data-plan="'+esc(p.id)+'"><span class="planCardIcon" aria-hidden="true">'+cat(p.category)[1]+'</span><span><b>'+esc(p.title)+'</b><small>'+esc(time(p.starts_at))+' · '+esc(p.venue_label)+'</small><span class="planBadges"><em>'+esc(p.status==='cancelled'?tr('Скасовано','Cancelled'):p.status==='ended'?tr('Завершено','Ended'):free?tr('Ще '+free+' місц.',''+free+' seats left'):tr('Місця зайняті','Full'))+'</em>'+(p.visibility==='private'?'<em>🔒 '+tr('Приватна локація','Private venue')+'</em>':'')+(status(p.my_status)?'<em>'+esc(status(p.my_status))+'</em>':'')+(p.pending_count?'<em class="planAccent">'+p.pending_count+' '+tr('заявок','requests')+'</em>':'')+'</span></span><i aria-hidden="true">›</i></button>';}
  function bindCards(){root.querySelectorAll('[data-plan]').forEach(button=>button.onclick=()=>openDetail(button.dataset.plan));}
  function whenLabel(){
    if(!when)return '<span>'+tr('Дата й час','Date & time')+'</span>';
    const date=new Date(when.date+'T12:00').toLocaleDateString(getLang()==='en'?'en-GB':'uk-UA',{day:'numeric',month:'short'});
    return '<span><b>'+esc(date)+'</b><small>'+esc(when.allDay?tr('Увесь день','All day'):when.from+'–'+when.to)+'</small></span>';
  }
  function chooseWhen(){
    const selected=when?{...when}:{date:vybePlanLocalDate(),allDay:true,from:'18:00',to:'23:00'};
    const today=vybePlanLocalDate(),latest=new Date();latest.setDate(latest.getDate()+90);const max=vybePlanLocalDate(latest);
    page(top(tr('Коли зустрічаємося?','When shall we meet?'),tr('Обери дату та зручний час.','Choose a date and a convenient time.'))+
      '<div class="planScroll"><form id="planWhenForm" class="planForm planDateForm">'+
      '<label class="planLabel" for="planFilterDate">'+tr('Дата','Date')+'<input id="planFilterDate" type="date" required min="'+today+'" max="'+max+'" value="'+esc(selected.date)+'"></label>'+
      '<label class="planAllDay" for="planFilterAllDay"><span>'+tr('Увесь день','All day')+'</span><input id="planFilterAllDay" type="checkbox" '+(selected.allDay?'checked':'')+'></label>'+
      '<div id="planFilterTimes" class="planFieldPair" '+(selected.allDay?'hidden':'')+'><label class="planLabel" for="planFilterFrom">'+tr('Час від','From')+'<input id="planFilterFrom" type="time" step="60" value="'+esc(selected.from)+'"></label><label class="planLabel" for="planFilterTo">'+tr('Час до','Until')+'<input id="planFilterTo" type="time" step="60" value="'+esc(selected.to)+'"></label></div>'+
      '<p class="planHint">'+tr('Покажемо плани, що починаються у вибраний день і час. Час — за налаштуваннями твого пристрою.','Shows plans starting on the selected date and within the chosen time window. Times follow your device settings.')+'</p><p id="planWhenError" class="planError" role="alert" hidden></p></form></div>'+
      '<footer class="planFooter planDateFooter"><button id="planWhenReset" type="button" class="choice">'+tr('Скинути','Reset')+'</button><button type="submit" form="planWhenForm" class="primary">'+tr('Показати плани','Show plans')+'</button></footer>','when');
    const toggle=()=>{const allDay=find('planFilterAllDay').checked;find('planFilterTimes').hidden=allDay;for(const id of ['planFilterFrom','planFilterTo']){find(id).disabled=allDay;find(id).required=!allDay;}};
    find('planFilterAllDay').onchange=toggle;toggle();
    find('planWhenReset').onclick=()=>{when=null;browse(previous);};
    find('planWhenForm').onsubmit=event=>{
      event.preventDefault();const next={date:find('planFilterDate').value,allDay:find('planFilterAllDay').checked,from:find('planFilterFrom').value,to:find('planFilterTo').value};
      const error=find('planWhenError');
      if(next.date<today||next.date>max||!vybePlanTimeRange(next)){error.hidden=false;error.textContent=tr('Обери дату в межах 90 днів. Час «до» має бути пізнішим за «від» у той самий день.','Choose a date within 90 days. The end time must be later than the start time on the same day.');return;}
      when=next;browse(previous);
    };
  }
  async function browse(mode=view==='list'?'list':'map'){
    previous=mode;detail=null;messageRetry=null;
    const token=page(top(tr('Зустрінемося?','Meet up?'),tr('Обери привід і знайди компанію.','Pick a plan and find your people.'),false)+
      '<div class="planModes"><button id="planPeople" type="button">'+tr('Люди','People')+'</button><button type="button" class="selected" aria-current="page">'+tr('Плани','Plans')+'</button><button id="planMine" type="button">'+tr('Мої плани','My plans')+'</button></div>'+
      '<div class="planFilters"><label class="srOnly" for="planCategory">'+tr('Категорія','Category')+'</label><select id="planCategory"><option value="">'+tr('Усі плани','All plans')+'</option>'+options(category)+'</select><button id="planWhen" type="button" class="planWhenFilter '+(when?'selected':'')+'" aria-label="'+tr('Обрати дату й час','Choose date and time')+'"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18"/></svg>'+whenLabel()+'<i aria-hidden="true">›</i></button></div>'+
      '<div class="planBrowseTools"><label class="srOnly" for="planCity">'+tr('Місто','City')+'</label><select id="planCity"><option value="">'+tr('Перейти до міста','Go to city')+'</option>'+mapCityOptions()+'</select><button id="planToggle" type="button">'+(mode==='map'?tr('☷ Список','☷ List'):tr('📍 Карта','📍 Map'))+'</button></div>'+
      (mode==='map'?'<div class="planMapWrap"><div id="planMap" class="planMap" role="region" aria-label="'+tr('Карта планів','Plans map')+'"></div><div id="planMapNotice" class="planMapNotice" role="status">'+tr('Завантаження карти…','Loading map…')+'</div></div><div id="planPreview" class="planPreview" role="status"></div>':'<div id="planList" class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div>')+
      '<footer class="planFooter"><button id="planCreate" type="button" class="primary">＋ '+tr('Створити план','Create a plan')+'</button></footer>',mode);
    find('planPeople').onclick=()=>onPeople();find('planMine').onclick=myPlans;
    find('planToggle').onclick=()=>browse(mode==='map'?'list':'map');find('planCreate').onclick=createForm;
    find('planCategory').onchange=event=>{category=event.target.value;load();};find('planWhen').onclick=chooseWhen;
    find('planCity').onchange=event=>{const city=VYBE_MAP_CITIES[Number(event.target.value)];if(event.target.value===''||!city)return;center=[city[2],city[3]];if(map)map.setView(center,12);else browse(mode);};
    let fetchToken=0;
    const bounds=()=>{if(!map){const c=center||mapCityCenter(getProfile()?.city);return {south:Math.max(-85,c[0]-.18),north:Math.min(85,c[0]+.18),west:Math.max(-180,c[1]-.25),east:Math.min(180,c[1]+.25)};}const b=map.getBounds();return {south:Math.max(-85,b.getSouth()),north:Math.min(85,b.getNorth()),west:((b.getWest()+180)%360+360)%360-180,east:((b.getEast()+180)%360+360)%360-180};};
    async function load(){const request=++fetchToken;const result=await api('plans_list',{category,...(when?vybePlanTimeRange(when):{}),bounds:bounds()});if(!alive(token)||request!==fetchToken)return;
      const target=mode==='map'?find('planPreview'):find('planList');if(!result.ok){target.innerHTML='<p class="planEmpty">'+esc(errorText(result.error))+'</p><button id="planRetry" type="button" class="choice">'+tr('Спробувати ще раз','Try again')+'</button>';find('planRetry').onclick=load;return;}
      plans=result.plans||[];
      if(mode==='map'){
        target.innerHTML='<button id="planShowList" type="button" class="planShowList">'+esc(plans.length?tr('Планів у цій ділянці: '+plans.length,'Plans in this area: '+plans.length):tr('Тут ще немає планів. Створи перший!','No plans here yet. Create the first!'))+' ›</button>';
        find('planShowList').onclick=()=>browse('list');
        if(markers){markers.clearLayers();for(const p of plans){const marker=L.marker([Number(p.map_lat),Number(p.map_lng)],{icon:L.divIcon({className:'planPin',html:'<span>'+cat(p.category)[1]+'</span>',iconSize:[40,44],iconAnchor:[20,40]}),title:p.title}).addTo(markers);marker.on('click',()=>openDetail(p.id));}}
      }else{target.innerHTML=plans.length?plans.map(card).join(''):'<div class="planEmpty"><b>'+tr('Будь приводом зустрітися','Be the reason to meet')+'</b><p>'+tr('Піца після роботи, прогулянка чи день народження — створи свій план або зміни фільтри.','Pizza after work, a walk, or a birthday — create a plan or change the filters.')+'</p></div>';bindCards();}
    }
    if(mode==='map'){
      try{const lib=await loadLeaflet();if(!alive(token))return;map=lib.map(find('planMap'),{minZoom:3,maxZoom:17,maxBounds:[[-85,-180],[85,180]],maxBoundsViscosity:1,zoomControl:false}).setView(center||mapCityCenter(getProfile()?.city),zoom);lib.control.zoom({position:'bottomleft'}).addTo(map);
        lib.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(map).on('tileerror',()=>{if(alive(token)){find('planMapNotice').hidden=false;find('planMapNotice').textContent=tr('Фон карти недоступний. Плани є у списку.','Map tiles unavailable. Use the list.');}});
        markers=lib.layerGroup().addTo(map);find('planMapNotice').hidden=true;map.on('moveend',()=>{clearTimeout(timer);timer=setTimeout(load,450);});map.invalidateSize();
      }catch{if(alive(token))find('planMapNotice').textContent=tr('Карта недоступна. Перейди до списку.','Map unavailable. Switch to the list.');}
    }
    if(alive(token))await load();
  }
  async function myPlans(){previous='my';const token=page(top(tr('Мої плани','My plans'),tr('Твої зустрічі та заявки','Your meetups and requests'))+'<div id="planList" class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div><footer class="planFooter"><button id="planCreate" type="button" class="primary">＋ '+tr('Створити план','Create a plan')+'</button></footer>','my');find('planCreate').onclick=createForm;const result=await api('plans_my');if(!alive(token))return;find('planList').innerHTML=result.ok?(result.plans?.length?result.plans.map(card).join(''):'<p class="planEmpty">'+tr('Твої плани та заявки зʼявляться тут.','Your plans and requests will appear here.')+'</p>'):'<p class="planEmpty">'+esc(errorText(result.error))+'</p><button id="planRetry" class="choice">'+tr('Спробувати ще раз','Try again')+'</button>';if(find('planRetry'))find('planRetry').onclick=myPlans;bindCards();}
  function newDraft(){const date=new Date(Date.now()+2*3600000);date.setSeconds(0,0);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);return {category:'pizza',title:'',description:'',city:getProfile()?.city||'Київ',venue_label:'',visibility:'public',meeting_details:'',starts_at:local,duration_hours:2,capacity:2,point:null,nonce:nonce(),submitted:null};}
  function collect(){if(!draft)return;for(const key of ['category','title','description','city','venue_label','visibility','meeting_details','starts_at','duration_hours','capacity']){const el=find('planField_'+key);if(el)draft[key]=el.value;}}
  function createForm(){if(!draft)draft=newDraft();const fields=(key,label,html)=>'<label class="planLabel" for="planField_'+key+'">'+esc(label)+html+'</label>';
    const token=page(top(tr('Твій привід зустрітися','Your reason to meet'),tr('До 20 людей разом з тобою','Up to 20 people, including you'))+'<div class="planScroll"><form id="planForm" class="planForm">'+
      fields('category',tr('Що робимо?','What are we doing?'),'<select id="planField_category">'+options(draft.category)+'</select>')+
      fields('title',tr('Назва плану','Plan title'),'<input id="planField_title" required minlength="3" maxlength="80" placeholder="'+tr('Наприклад: піца і розмова сьогодні','e.g. pizza and a chat tonight')+'" value="'+esc(draft.title)+'">')+
      fields('description',tr('Розкажи про ідею','Tell us about your idea'),'<textarea id="planField_description" maxlength="500" rows="3" placeholder="'+tr('Атмосфера, спільний рахунок, що взяти із собою…','The vibe, splitting the bill, what to bring…')+'">'+esc(draft.description)+'</textarea>')+
      fields('starts_at',tr('Дата і час','Date and time'),'<input id="planField_starts_at" type="datetime-local" required value="'+esc(draft.starts_at)+'">')+
      '<div class="planFieldPair">'+fields('duration_hours',tr('Тривалість','Duration'),'<select id="planField_duration_hours">'+[1,2,3,4,6,8,12,24].map(x=>'<option value="'+x+'" '+(Number(draft.duration_hours)===x?'selected':'')+'>'+x+' '+tr('год','h')+'</option>').join('')+'</select>')+fields('capacity',tr('Людей разом з тобою','People including you'),'<input id="planField_capacity" type="number" min="2" max="20" required value="'+esc(draft.capacity)+'">')+'</div>'+
      fields('city',tr('Місто','City'),'<input id="planField_city" required maxlength="64" value="'+esc(draft.city)+'">')+
      fields('visibility',tr('Локація','Venue'),'<select id="planField_visibility"><option value="public" '+(draft.visibility==='public'?'selected':'')+'>'+tr('Публічна: заклад, парк, природа','Public: venue, park, outdoors')+'</option><option value="private" '+(draft.visibility==='private'?'selected':'')+'>'+tr('Приватна: квартира, будинок','Private: apartment, house')+'</option></select>')+
      '<p id="planLocationHint" class="planHint"></p>'+fields('venue_label',tr('Місце або район — видно всім','Venue or area — visible to everyone'),'<input id="planField_venue_label" required minlength="2" maxlength="80" value="'+esc(draft.venue_label)+'" placeholder="'+tr('Назва закладу або лише район','Venue name or area only')+'">')+
      '<button id="planPick" class="choice" type="button">📍 '+esc(draft.point?tr('Локацію обрано · змінити','Location selected · change'):tr('Обрати місце на карті','Choose a location on the map'))+'</button>'+
      fields('meeting_details',tr('Де саме зустрічаємося — лише учасникам','Meeting details — members only'),'<textarea id="planField_meeting_details" required minlength="2" maxlength="300" rows="2" placeholder="'+tr('Вхід, орієнтир або приватна адреса','Entrance, landmark, or private address')+'">'+esc(draft.meeting_details)+'</textarea>')+
      '<p class="planHint">'+tr('Усі заявки схвалюєш ти. Адреса й чат відкриються лише після схвалення. Для приватної локації не додавай адресу до назви чи опису.','You approve every request. Meeting details and chat unlock after approval. For a private venue, keep the address out of the title and description.')+'</p><p id="planError" class="planError" role="alert" hidden></p><button id="planPublish" type="submit" class="primary">'+tr('Опублікувати план','Publish plan')+'</button></form></div>','create');
    const privacyHint=()=>{collect();find('planLocationHint').textContent=draft.visibility==='private'?tr('На карті буде приблизний район у кілька кілометрів.','The map will show an approximate area spanning a few kilometres.'):tr('Позначка публічного місця округлюється приблизно до 100 м.','The public venue pin is rounded to roughly 100 m.');};find('planField_visibility').onchange=privacyHint;privacyHint();
    find('planPick').onclick=()=>{collect();pickLocation();};
    find('planForm').onsubmit=async event=>{event.preventDefault();if(busy)return;collect();const error=find('planError');if(!draft.point){error.hidden=false;error.textContent=tr('Спершу обери місце на карті.','Choose a location on the map first.');find('planPick').focus();return;}
      const starts=new Date(draft.starts_at);if(!Number.isFinite(starts.getTime())||starts.getTime()<=Date.now()||starts.getTime()>Date.now()+90*86400000){error.hidden=false;error.textContent=errorText('INVALID_PLAN_TIME');return;}
      const data={category:draft.category,title:draft.title.trim(),description:draft.description.trim(),city:draft.city.trim(),venue_label:draft.venue_label.trim(),visibility:draft.visibility,meeting_details:draft.meeting_details.trim(),starts_at:starts.toISOString(),duration_hours:Number(draft.duration_hours),capacity:Number(draft.capacity),map_lat:draft.point.lat,map_lng:draft.point.lng};
      const fingerprint=JSON.stringify(data);if(draft.submitted&&draft.submitted!==fingerprint)draft.nonce=nonce();draft.submitted=fingerprint;
      busy=true;find('planPublish').disabled=true;error.hidden=true;
      const result=await api('plans_create',{...data,client_nonce:draft.nonce});if(!alive(token))return;busy=false;
      if(!result.ok){find('planPublish').disabled=false;error.hidden=false;error.textContent=errorText(result.error);return;}
      analytics('plan_created',{category:data.category,visibility:data.visibility});draft=null;await openDetail(result.plan.id);
    };
  }
  async function pickLocation(){let tileFailed=false;const privatePlace=draft.visibility==='private';const token=page(top(tr('Обери локацію','Choose the location'),privatePlace?tr('Лише приблизний район буде публічним','Only an approximate area will be public'):tr('Наведи центр на місце зустрічі','Move the centre to the meeting place'))+'<div class="planBrowseTools"><label class="srOnly" for="planCity">'+tr('Місто','City')+'</label><select id="planCity"><option value="">'+tr('Перейти до міста','Go to city')+'</option>'+mapCityOptions()+'</select></div><div class="planMapWrap"><div id="planMap" class="planMap"></div><div class="planCrosshair" aria-hidden="true">＋</div><p id="planMapNotice" class="planMapNotice" role="status">'+tr('Завантаження карти…','Loading map…')+'</p></div><footer class="planFooter"><p class="planHint">'+tr('OpenStreetMap отримує IP-адресу та ділянку карти.','OpenStreetMap receives your IP address and map area.')+'</p><button id="planPickConfirm" type="button" class="primary" disabled>'+tr('Обрати це місце','Choose this location')+'</button></footer>','pick');
    try{const lib=await loadLeaflet();if(!alive(token))return;const c=draft.point?[draft.point.lat,draft.point.lng]:mapCityCenter(draft.city);map=lib.map(find('planMap'),{minZoom:3,maxZoom:18,maxBounds:[[-85,-180],[85,180]],maxBoundsViscosity:1,zoomControl:false}).setView(c,privatePlace?12:16);lib.control.zoom({position:'bottomleft'}).addTo(map);lib.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(map).on('tileerror',()=>{tileFailed=true;if(alive(token)){find('planMapNotice').hidden=false;find('planMapNotice').textContent=tr('Фон карти не завантажено. Спробуй ще раз.','Map tiles did not load. Please try again.');find('planPickConfirm').disabled=true;}}).on('loading',()=>{tileFailed=false;if(alive(token))find('planPickConfirm').disabled=true;}).on('load',()=>{if(alive(token)&&!tileFailed){find('planMapNotice').hidden=true;find('planPickConfirm').disabled=false;}});
      find('planCity').onchange=event=>{if(event.target.value==='')return;const c=VYBE_MAP_CITIES[Number(event.target.value)];map.setView([c[2],c[3]],privatePlace?12:16);};
      map.on('click',event=>map.panTo(event.latlng));let area=null;if(privatePlace){const draw=()=>{area?.remove();const p=snapMapPoint(map.getCenter().lat,map.getCenter().lng);if(p)area=lib.rectangle([[p.lat-.025,p.lng-.025],[p.lat+.025,p.lng+.025]],{color:'#bcafff',weight:1,fillOpacity:.12}).addTo(map);};map.on('moveend',draw);draw();}
      find('planPickConfirm').onclick=()=>{const c=map.getCenter();draft.point={lat:Math.max(-85,Math.min(85,c.lat)),lng:((c.lng+180)%360+360)%360-180};createForm();};map.invalidateSize();
    }catch{if(alive(token))find('planMapNotice').textContent=tr('Не вдалося завантажити карту. Повернися й спробуй ще раз.','Could not load the map. Go back and try again.');}
  }
  async function openDetail(id){const token=page(top(tr('План зустрічі','Meetup plan'))+'<div class="planScroll"><p class="planEmpty">'+tr('Завантаження…','Loading…')+'</p></div>','detail');detail={id};const result=await api('plans_get',{plan_id:id});if(!alive(token))return;if(!result.ok){root.innerHTML=top(tr('План недоступний','Plan unavailable'))+'<p class="planEmpty">'+esc(errorText(result.error))+'</p><button id="planRetry" class="choice">'+tr('Спробувати ще раз','Try again')+'</button>';find('planBack').onclick=back;find('planRetry').onclick=()=>openDetail(id);return;}detail=result;renderDetail(result,token);
    refreshTimer=setInterval(async()=>{if(!alive(token)||document.visibilityState!=='visible'||busy)return;const r=await api('plans_get',{plan_id:id});if(!alive(token))return;if(!r.ok){clearInterval(refreshTimer);refreshTimer=null;root.innerHTML=top(tr('План недоступний','Plan unavailable'))+'<p class="planEmpty">'+esc(errorText(r.error))+'</p>';find('planBack').onclick=back;return;}const message=find('planMessage')?.value||'',note=find('planNote')?.value||'';const active=document.activeElement?.id,selection=document.activeElement?.selectionStart;const scroll=find('planDetailScroll')?.scrollTop||0;const changed=JSON.stringify(r)!==JSON.stringify(detail);if(!changed)return;detail=r;renderDetail(r,token);if(find('planMessage'))find('planMessage').value=message;if(find('planNote'))find('planNote').value=note;const el=active&&find(active);if(el&&typeof selection==='number'){el.focus({preventScroll:true});el.setSelectionRange?.(selection,selection);}if(find('planDetailScroll'))find('planDetailScroll').scrollTop=scroll;},15000);
  }
  function renderDetail(result,token){const p=result.plan,host=p.my_status==='host',member=host||p.my_status==='approved',open=p.status==='active';
    const profileButton=profile=>'<button type="button" class="planPerson" '+(profile.unavailable?'disabled':'data-profile="'+esc(profile.user_id)+'"')+'>'+(profile.photo_url?'<img src="'+esc(profile.photo_url)+'" alt="" loading="lazy">':'<span class="planAvatar">'+esc((profile.name||'V').slice(0,1))+'</span>')+'<span>'+esc(profile.unavailable?tr('Учасник недоступний','Member unavailable'):profile.name)+'<small>'+esc(profile.age||'')+'</small></span></button>';
    root.innerHTML=top(catLabel(p.category))+'<div id="planDetailScroll" class="planScroll"><article class="planDetail"><h3>'+esc(p.title)+'</h3><p class="planWhen">'+esc(time(p.starts_at))+'</p><div class="planBadges"><em>'+p.approved_count+'/'+p.capacity+' '+tr('людей','people')+'</em><em>'+esc(p.city)+'</em><em>'+(p.visibility==='private'?'🔒 '+tr('Приватна локація','Private venue'):tr('Публічна локація','Public venue'))+'</em></div><p class="planVenue">📍 '+esc(p.venue_label)+'</p><p class="planDescription">'+esc(p.description)+'</p>'+profileButton(p.host)+'<p class="planHint">'+tr('Організатор','Host')+'</p>'+
      (open&&member&&p.meeting_details?'<div class="planAddress"><b>🔑 '+tr('Де зустрічаємося','Where to meet')+'</b><p>'+esc(p.meeting_details)+'</p><small>'+tr('Лише для схвалених учасників','Approved members only')+'</small></div>':'<p class="planHint">'+esc(!open?(p.status==='cancelled'?tr('План скасовано.','Plan cancelled.'):tr('Зустріч завершилася.','This meetup has ended.')):tr('Точне місце й спільний чат відкриються після схвалення заявки.','Meeting details and group chat unlock after the host approves your request.'))+'</p>')+
      (open&&!host&&!member&&p.my_status!=='rejected'?(p.my_status==='pending'?'<div class="planAddress"><b>'+status('pending')+'</b><p>'+tr('Організатор отримає твою заявку. Відповідь зʼявиться тут і у сповіщеннях.','The host will receive your request. The reply appears here and in notifications.')+'</p></div>':'<label class="planLabel" for="planNote">'+tr('Кілька слів організатору','A few words for the host')+'<textarea id="planNote" rows="2" maxlength="200" placeholder="'+tr('Що цікавить у цій зустрічі?','What interests you about this meetup?')+'"></textarea></label><button id="planApply" type="button" class="primary" '+(p.approved_count>=p.capacity?'disabled':'')+'>'+tr(p.approved_count>=p.capacity?'Місця зайняті':'Хочу приєднатися',p.approved_count>=p.capacity?'All seats taken':'I want to join')+'</button>'):'')+
      (p.my_status==='rejected'?'<p class="planHint">'+esc(status('rejected'))+'</p>':'')+
      (open&&member?'<div class="planExtrasActions"><button id="planInvite" class="choice" type="button">'+tr(host?'Запрошення на план':'Поділитися планом',host?'Plan invitation':'Share plan')+'</button><button id="planPlanning" class="choice" type="button">'+tr('Календар і нагадування','Calendar and reminder')+'</button></div>':'')+
      (host&&open?'<section class="planRequests"><h4>'+tr('Заявки та учасники','Requests and members')+'</h4>'+(result.requests.length?result.requests.map(a=>'<div class="planRequest">'+profileButton(a.profile)+'<p>'+esc(a.note)+'</p><small>'+esc(a.status==='pending'?tr('Очікує рішення','Awaiting approval'):tr('Схвалено','Approved'))+'</small><div class="planRequestActions">'+(a.status==='pending'?'<button type="button" class="primary" data-approve="'+esc(a.user_id)+'">'+tr('Прийняти','Approve')+'</button>':'')+'<button type="button" class="choice" data-reject="'+esc(a.user_id)+'">'+(a.status==='approved'?tr('Прибрати','Remove'):tr('Відхилити','Decline'))+'</button></div></div>').join(''):'<p class="planHint">'+tr('Поки немає заявок.','No requests yet.')+'</p>')+'</section>':'')+
      (member?'<section><h4>'+tr('Компанія','Your company')+'</h4><div class="planMembers">'+result.members.map(profileButton).join('')+'</div><h4>'+tr('Домовимося тут','Make plans here')+'</h4><div id="planMessages" class="planMessages">'+(result.messages.length?result.messages.map(m=>'<div class="planMessage"><button type="button" data-profile="'+esc(m.sender_id)+'">'+esc(m.sender?.name||'VYBE')+'</button><p>'+esc(m.body)+'</p><small>'+esc(time(m.created_at))+'</small></div>').join(''):'<p class="planHint">'+tr('Чат бачать лише організатор і схвалені учасники.','Only the host and approved members can see this chat.')+'</p>')+'</div>'+(result.can_chat?'<form id="planMessageForm" class="planMessageForm"><label class="srOnly" for="planMessage">'+tr('Повідомлення','Message')+'</label><textarea id="planMessage" maxlength="1000" rows="2" required placeholder="'+tr('Домовтеся про деталі…','Discuss the details…')+'"></textarea><button id="planSend" class="primary" type="submit">'+tr('Надіслати','Send')+'</button></form>':'')+'</section>':'')+
      '<p id="planError" class="planError" role="alert" hidden></p><div class="planDetailActions">'+(open?(host?'<button id="planCancel" class="choice planDanger" type="button">'+tr('Скасувати план','Cancel plan')+'</button>':p.my_status==='pending'||member?'<button id="planLeave" class="choice" type="button">'+tr('Вийти з плану','Leave plan')+'</button>':''):'')+(!host?'<button id="planSafety" class="choice" type="button">🛡 '+tr('Безпека','Safety')+'</button>':'')+'</div><p class="planHint">'+tr('Першу зустріч краще провести в публічному місці.','Choose a public place for your first meeting.')+'</p></article></div>';
    find('planBack').onclick=back;root.querySelectorAll('[data-profile]').forEach(button=>button.onclick=()=>onProfile(button.dataset.profile,p.id));find('planSafety')?.addEventListener('click',()=>onSafety(p.owner_id,p.host?.name,p.id));
    async function act(action,data={}){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);const r=await api(action,{plan_id:p.id,...data});if(!alive(token))return;busy=false;if(!r.ok){root.querySelectorAll('button').forEach(b=>b.disabled=false);const error=find('planError');error.hidden=false;error.textContent=errorText(r.error);return;}if(action==='plans_apply')analytics('plan_request_sent',{category:p.category});await openDetail(p.id);}
    find('planInvite')?.addEventListener('click',()=>onExtras(p.id,host,'invitation'));
    find('planPlanning')?.addEventListener('click',()=>onExtras(p.id,host,'planning'));
    find('planApply')?.addEventListener('click',()=>act('plans_apply',{note:find('planNote')?.value||''}));
    root.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>act('plans_respond',{user_id:b.dataset.approve,decision:'approved'}));
    root.querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{if(await confirm(tr('Відхилити заявку або прибрати учасника?','Decline this request or remove this member?'))&&alive(token))act('plans_respond',{user_id:b.dataset.reject,decision:'rejected'});});
    find('planCancel')?.addEventListener('click',async()=>{if(await confirm(tr('Скасувати план для всіх учасників?','Cancel this plan for everyone?'))&&alive(token))act('plans_cancel');});
    find('planLeave')?.addEventListener('click',()=>act('plans_leave'));
    find('planMessageForm')?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const body=find('planMessage').value.trim();if(!body)return;if(!messageRetry||messageRetry.body!==body||messageRetry.plan_id!==p.id)messageRetry={plan_id:p.id,body,client_nonce:nonce()};busy=true;find('planSend').disabled=true;find('planMessage').readOnly=true;const r=await api('plans_message',messageRetry);if(!alive(token))return;busy=false;if(!r.ok){find('planSend').disabled=false;find('planMessage').readOnly=false;find('planError').hidden=false;find('planError').textContent=errorText(r.error);return;}messageRetry=null;await openDetail(p.id);});
  }
  function back(){if(closed||!root?.isConnected)return false;if(view==='when'){browse(previous);return true;}if(view==='pick'){createForm();return true;}if(view==='create'){collect();if(previous==='my')myPlans();else browse(previous);return true;}if(view==='detail'){if(previous==='my')myPlans();else browse(previous);return true;}if(view==='my'){browse('map');return true;}return false;}
  function exit(event){if(event.target.closest?.('#planExit'))onExit();}
  function mount(target,initialId){dispose();root=target;root.addEventListener('click',exit);closed=false;center=mapCityCenter(getProfile()?.city);previous='map';if(initialId)openDetail(initialId);else browse('map');}
  return {mount,dispose,back,isMounted:()=>!closed&&!!root?.isConnected};
}
