-- Synthetic accounts only; nothing is committed and no Telegram calls occur.
begin;
set local role service_role;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();plan uuid;token uuid;calendar uuid;r jsonb;jobs jsonb;job jsonb;seed bigint:=-930000000000-floor(random()*10000000000)::bigint;
begin
  if has_table_privilege('anon','public.vybe_plan_invites','SELECT') or has_table_privilege('authenticated','public.vybe_plan_reminders','UPDATE')
    or has_function_privilege('anon','public.vybe_plan_invite_preview(uuid,uuid)','EXECUTE') or has_function_privilege('authenticated','public.vybe_plan_reminder_claim()','EXECUTE') then raise exception 'Growth data exposed to client roles';end if;
  insert into public.users(id,telegram_id,first_name) values(a,seed,'Invite QA A'),(b,seed-1,'Invite QA B'),(c,seed-2,'Invite QA C');
  insert into public.profiles(user_id,name,age,city,gender,looking_for,bio,photo_url)
    select x,'Invite QA',28,'Київ','Чоловік','Усіх','Rollback QA profile',x::text||'/qa.jpg' from unnest(array[a,b]) x;
  insert into public.notification_preferences(user_id,likes_enabled,matches_enabled,messages_enabled) values(a,true,true,true),(b,true,true,true);
  r:=public.vybe_plan(a,'create',jsonb_build_object('client_nonce',gen_random_uuid(),'category','pizza','title','Invitation QA pizza','description','PRIVATE DESCRIPTION','city','Київ','venue_label','SECRET PRIVATE VENUE LABEL','visibility','private','meeting_details','SECRET ADDRESS','map_lat',50.45234,'map_lng',30.51345,'starts_at',now()+interval '30 minutes','duration_hours',2,'capacity',3));
  plan:=(r->'plan'->>'id')::uuid;
  if (public.vybe_plan_growth(a,'invite_get',plan)->>'enabled')::boolean then raise exception 'Existing plan auto-published';end if;
  begin perform public.vybe_plan_growth(b,'invite_update',plan,true);raise exception 'Outsider published invitation';exception when insufficient_privilege then null;end;
  begin perform public.vybe_plan_growth(a,'share',plan);raise exception 'Shared without consent';exception when insufficient_privilege then null;end;
  perform public.vybe_plan_growth(a,'invite_update',plan,true);
  token:=(public.vybe_plan_growth(a,'share',plan)->>'token')::uuid;
  r:=public.vybe_plan_invite_preview(token,null);
  if r is null or r::text like '%SECRET%' or r::text like '%PRIVATE DESCRIPTION%' or r ? 'host' or r ? 'map_lat' or r ? 'members' then raise exception 'Preview leaks private fields';end if;
  if public.vybe_plan_invite_preview(token,c) is null then raise exception 'Preview requires a completed profile';end if;
  if public.vybe_plan_invite_preview(gen_random_uuid(),null) is not null then raise exception 'Unknown invitation accepted';end if;
  perform public.vybe_plan_growth(a,'invite_update',plan,false);
  if public.vybe_plan_invite_preview(token,null) is not null then raise exception 'Disabled link still works';end if;
  perform public.vybe_plan_growth(a,'invite_update',plan,true);
  if public.vybe_plan_invite_preview(token,null) is not null then raise exception 'Old link restored after enabling';end if;
  token:=(public.vybe_plan_growth(a,'share',plan)->>'token')::uuid;
  begin perform public.vybe_plan_growth(b,'calendar',plan);raise exception 'Outsider downloaded calendar';exception when insufficient_privilege then null;end;
  begin perform public.vybe_plan_growth(b,'reminder_set',plan,true);raise exception 'Outsider enabled reminder';exception when insufficient_privilege then null;end;
  perform public.vybe_plan(b,'apply',jsonb_build_object('plan_id',plan,'note','SECRET APPLICATION NOTE'));
  begin perform public.vybe_plan_growth(b,'calendar',plan);raise exception 'Pending applicant got calendar';exception when insufficient_privilege then null;end;
  perform public.vybe_plan(a,'respond',jsonb_build_object('plan_id',plan,'user_id',b,'decision','approved'));
  calendar:=(public.vybe_plan_growth(b,'calendar',plan)->>'token')::uuid;
  if public.vybe_plan_calendar_export(calendar) is null or public.vybe_plan_calendar_export(calendar)::text like '%SECRET%' then raise exception 'Calendar export missing or leaks location';end if;
  if (public.vybe_plan_growth(b,'reminder_get',plan)->>'enabled')::boolean then raise exception 'Reminder enabled without opt-in';end if;
  perform public.vybe_plan_growth(b,'reminder_set',plan,true);
  perform public.vybe_plan_growth(b,'reminder_set',plan,true);
  jobs:=public.vybe_plan_reminder_claim();
  select x into job from jsonb_array_elements(jobs) x where x->>'plan_id'=plan::text and x->>'user_id'=b::text;
  if job is null or not public.vybe_plan_reminder_allowed(plan,b,(job->>'claim')::uuid) then raise exception 'Eligible reminder was not claimed';end if;
  if exists(select 1 from jsonb_array_elements(public.vybe_plan_reminder_claim()) x where x->>'plan_id'=plan::text) then raise exception 'Reminder claimed twice';end if;
  if (select count(*) from public.notification_events where source_key='plan:reminder:'||plan||':'||b)<>1 then raise exception 'Duplicate reminder event';end if;
  update public.notification_preferences set messages_enabled=false where user_id=b;
  if public.vybe_plan_reminder_allowed(plan,b,(job->>'claim')::uuid) then raise exception 'Telegram preference ignored';end if;
  update public.notification_preferences set messages_enabled=true where user_id=b;
  perform public.vybe_plan_growth(b,'reminder_set',plan,false);
  if public.vybe_plan_reminder_allowed(plan,b,(job->>'claim')::uuid) then raise exception 'Disabled reminder sent';end if;
  perform public.vybe_plan_growth(b,'reminder_set',plan,true);
  perform public.vybe_plan_reminder_finish(plan,b,(job->>'claim')::uuid,'retry',60);
  update public.vybe_plan_reminders set retry_at=now() where plan_id=plan and user_id=b;
  jobs:=public.vybe_plan_reminder_claim();select x into job from jsonb_array_elements(jobs) x where x->>'plan_id'=plan::text and x->>'user_id'=b::text;
  if job is null or (select count(*) from public.notification_events where source_key='plan:reminder:'||plan||':'||b)<>1 then raise exception 'Retry duplicated reminder event';end if;
  perform public.vybe_plan_reminder_finish(plan,b,(job->>'claim')::uuid,'sent',0);
  perform public.vybe_plan(b,'leave',jsonb_build_object('plan_id',plan));
  if public.vybe_plan_calendar_export(calendar) is not null or exists(select 1 from public.vybe_plan_reminders where plan_id=plan and user_id=b and enabled) then raise exception 'Leave retained calendar or reminder';end if;
  perform public.vybe_plan(b,'apply',jsonb_build_object('plan_id',plan));perform public.vybe_plan(a,'respond',jsonb_build_object('plan_id',plan,'user_id',b,'decision','approved'));
  if public.vybe_plan_calendar_export(calendar) is not null then raise exception 'Old calendar token restored on rejoining';end if;
  insert into public.blocks(blocker_id,blocked_id) values(c,a);
  if public.vybe_plan_invite_preview(token,c) is not null then raise exception 'Authenticated preview ignored block';end if;
  update public.users set account_status='restricted' where id=a;
  if public.vybe_plan_invite_preview(token,null) is not null then raise exception 'Restricted host still published';end if;
  update public.users set account_status='active' where id=a;
  update public.vybe_plans set starts_at=now()-interval '1 minute' where id=plan;
  if public.vybe_plan_invite_preview(token,null) is not null then raise exception 'Invitation survived meetup start';end if;
  update public.vybe_plans set starts_at=now()+interval '30 minutes' where id=plan;
  perform public.vybe_plan(a,'cancel',jsonb_build_object('plan_id',plan));
  if public.vybe_plan_invite_preview(token,null) is not null or public.vybe_plan_calendar_export(calendar) is not null then raise exception 'Cancelled plan remained downloadable';end if;
  if public.vybe_plan_worker_authorized(repeat('b',64)) then raise exception 'Wrong worker secret accepted';end if;
end;
$$;
reset role;
select 'Invitation consent, preview privacy, calendar revocation, reminder deduplication and preferences passed' as result;
rollback;
